"""Routing hints from ESPN team catalogs, September 2026; facts still require live feeds."""
TEAM_NAMES = frozenset({
    '49ers',
    '76ers',
    'aces',
    'anaheim ducks',
    'angels',
    'arizona cardinals',
    'arizona diamondbacks',
    'astros',
    'athletics',
    'atlanta braves',
    'atlanta dream',
    'atlanta falcons',
    'atlanta hawks',
    'avalanche',
    'baltimore orioles',
    'baltimore ravens',
    'bears',
    'bengals',
    'bills',
    'blackhawks',
    'blue jackets',
    'blue jays',
    'blues',
    'boston bruins',
    'boston celtics',
    'boston red sox',
    'braves',
    'brewers',
    'broncos',
    'brooklyn nets',
    'browns',
    'bruins',
    'buccaneers',
    'bucks',
    'buffalo bills',
    'buffalo sabres',
    'bulls',
    'calgary flames',
    'canadiens',
    'canucks',
    'capitals',
    'cardinals',
    'carolina hurricanes',
    'carolina panthers',
    'cavaliers',
    'celtics',
    'chargers',
    'charlotte hornets',
    'chicago bears',
    'chicago blackhawks',
    'chicago bulls',
    'chicago cubs',
    'chicago sky',
    'chicago white sox',
    'chiefs',
    'cincinnati bengals',
    'cincinnati reds',
    'cleveland browns',
    'cleveland cavaliers',
    'cleveland guardians',
    'clippers',
    'colorado avalanche',
    'colorado rockies',
    'colts',
    'columbus blue jackets',
    'commanders',
    'connecticut sun',
    'cowboys',
    'cubs',
    'dallas cowboys',
    'dallas mavericks',
    'dallas stars',
    'dallas wings',
    'denver broncos',
    'denver nuggets',
    'detroit lions',
    'detroit pistons',
    'detroit red wings',
    'detroit tigers',
    'devils',
    'diamondbacks',
    'dodgers',
    'dolphins',
    'dream',
    'ducks',
    'eagles',
    'edmonton oilers',
    'falcons',
    'fever',
    'fire',
    'flames',
    'florida panthers',
    'flyers',
    'giants',
    'golden knights',
    'golden state valkyries',
    'golden state warriors',
    'green bay packers',
    'grizzlies',
    'guardians',
    'hawks',
    'heat',
    'hornets',
    'houston astros',
    'houston rockets',
    'houston texans',
    'hurricanes',
    'indiana fever',
    'indiana pacers',
    'indianapolis colts',
    'islanders',
    'jacksonville jaguars',
    'jaguars',
    'jazz',
    'jets',
    'kansas city chiefs',
    'kansas city royals',
    'kings',
    'knicks',
    'kraken',
    'la clippers',
    'lakers',
    'las vegas aces',
    'las vegas raiders',
    'liberty',
    'lightning',
    'lions',
    'los angeles angels',
    'los angeles chargers',
    'los angeles dodgers',
    'los angeles kings',
    'los angeles lakers',
    'los angeles rams',
    'los angeles sparks',
    'lynx',
    'magic',
    'mammoth',
    'maple leafs',
    'mariners',
    'marlins',
    'mavericks',
    'memphis grizzlies',
    'mercury',
    'mets',
    'miami dolphins',
    'miami heat',
    'miami marlins',
    'milwaukee brewers',
    'milwaukee bucks',
    'minnesota lynx',
    'minnesota timberwolves',
    'minnesota twins',
    'minnesota vikings',
    'minnesota wild',
    'montreal canadiens',
    'mystics',
    'nashville predators',
    'nationals',
    'nets',
    'new england patriots',
    'new jersey devils',
    'new orleans pelicans',
    'new orleans saints',
    'new york giants',
    'new york islanders',
    'new york jets',
    'new york knicks',
    'new york liberty',
    'new york mets',
    'new york rangers',
    'new york yankees',
    'nuggets',
    'oilers',
    'oklahoma city thunder',
    'orioles',
    'orlando magic',
    'ottawa senators',
    'pacers',
    'packers',
    'padres',
    'panthers',
    'patriots',
    'pelicans',
    'penguins',
    'philadelphia 76ers',
    'philadelphia eagles',
    'philadelphia flyers',
    'philadelphia phillies',
    'phillies',
    'phoenix mercury',
    'phoenix suns',
    'pirates',
    'pistons',
    'pittsburgh penguins',
    'pittsburgh pirates',
    'pittsburgh steelers',
    'portland fire',
    'portland trail blazers',
    'predators',
    'raiders',
    'rams',
    'rangers',
    'raptors',
    'ravens',
    'rays',
    'red sox',
    'red wings',
    'reds',
    'rockets',
    'rockies',
    'royals',
    'sabres',
    'sacramento kings',
    'saints',
    'san antonio spurs',
    'san diego padres',
    'san francisco 49ers',
    'san francisco giants',
    'san jose sharks',
    'seahawks',
    'seattle kraken',
    'seattle mariners',
    'seattle seahawks',
    'seattle storm',
    'senators',
    'sharks',
    'sky',
    'sparks',
    'spurs',
    'st. louis blues',
    'st. louis cardinals',
    'stars',
    'steelers',
    'storm',
    'sun',
    'suns',
    'tampa bay buccaneers',
    'tampa bay lightning',
    'tampa bay rays',
    'tempo',
    'tennessee titans',
    'texans',
    'texas rangers',
    'thunder',
    'tigers',
    'timberwolves',
    'titans',
    'toronto blue jays',
    'toronto maple leafs',
    'toronto raptors',
    'toronto tempo',
    'trail blazers',
    'twins',
    'utah jazz',
    'utah mammoth',
    'valkyries',
    'vancouver canucks',
    'vegas golden knights',
    'vikings',
    'warriors',
    'washington capitals',
    'washington commanders',
    'washington mystics',
    'washington nationals',
    'washington wizards',
    'white sox',
    'wild',
    'wings',
    'winnipeg jets',
    'wizards',
    'yankees',
})
